"""empty message

Revision ID: 3873cd5aa7fa
Revises: 2c0b83ee1d7e
Create Date: 2022-02-26 00:17:56.677924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3873cd5aa7fa'
down_revision = '2c0b83ee1d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
